steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - apps/web/Dockerfile
      - --build-arg
      - VITE_API_URL=$_VITE_API_URL
      - -t
      - $_IMAGE_NAME
      - .

substitutions:
  _VITE_API_URL: http://localhost:8085
  _IMAGE_NAME: gcr.io/$PROJECT_ID/namis-web

images:
  - $_IMAGE_NAME
